import IMGhouse1 from "./image/1.jpeg";
import IMGhouse2 from "./image/2.jpeg";
const Database = [
  {
    id: "1",
    tensanpham: "V3-04",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
  {
    id: "2",
    tensanpham: "Boutique Villa D2a-02",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "",
    noithat: "bàn giao cơ bản ",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
  {
    id: "3",
    tensanpham: "Biệt thự đơn lập V3-98",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
  {
    id: "3",
    tensanpham: "Biệt thự đơn lập V3-267",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
  {
    id: "3",
    tensanpham: "",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
  {
    id: "3",
    tensanpham: "",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
];

export default Database;
