import IMGhouse1 from "./image/1.jpeg";
import IMGhouse2 from "./image/2.jpeg";
const Database = [
  {
    id: "V3-04",
    tensanpham: "V3-04",
    image: [IMGhouse1, IMGhouse2],
    diachi:
      "Khu dân cư và công viên Phước Thiện thuộc phường Long Bình và Long Thạnh Mỹ",
    sotang: 3,
    phongngu: 4,
    huongnha: "Đông Nam",
    huongbancong: "Đông Nam",
    trangthai: "Đã bàn giao",
    noithat: "Bàn giao cơ bản",
    loaihang: "",
    duongvao: "13",
    wc: 3,
    mattien: "10",
    kichthuocsan: "10x29",
    dientich: 293,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 54,
  },
  {
    id: "2",
    tensanpham: "Boutique Villa D2a-02",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "Đông Nam",
    huongbancong: "Đông Nam",
    trangthai: "Đã bàn giao",
    noithat: "bàn giao cơ bản ",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
  {
    id: "3",
    tensanpham: "Biệt thự đơn lập V3-98",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "Đông Nam",
    huongbancong: "Đông Nam",
    trangthai: "Đã bàn giao",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
  {
    id: "3",
    tensanpham: "Biệt thự đơn lập V3-267",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "Đông Nam",
    huongbancong: "Đông Nam",
    trangthai: "Đã bàn giao",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
  {
    id: "3",
    tensanpham: "",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "Đông Nam",
    huongbancong: "Đông Nam",
    trangthai: "Đã bàn giao",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
  {
    id: "3",
    tensanpham: "",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: 4,
    huongnha: "Đông Nam",
    huongbancong: "Đông Nam",
    trangthai: "Đã bàn giao",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: 3,
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 20,
  },
];

export default Database;
