import IMGhouse1 from "./image/1.jpeg";
import IMGhouse2 from "./image/2.jpeg";
const Database = [
  {
    id: "1",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: "",
    huongnha: "",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: "",
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 100000,
  },
  {
    id: "2",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: "",
    huongnha: "",
    noithat: "bàn giao cơ bản ",
    loaihang: "",
    duongvao: "",
    wc: "",
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 1000000,
  },{
    id: "3",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: "",
    huongnha: "",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: "",
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 1000000,
  },
  {
    id: "3",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: "",
    huongnha: "",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: "",
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 1000000,
  },
  {
    id: "3",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: "",
    huongnha: "",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: "",
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 1000000,
  },
  {
    id: "3",
    image: [IMGhouse1, IMGhouse2],
    diachi: "House 1",
    sotang: 3,
    phongngu: "",
    huongnha: "",
    noithat: "bàn giao cơ bản",
    loaihang: "",
    duongvao: "",
    wc: "",
    mattien: "",
    kichthuocsan: "",
    dientich: 200,
    dacdiemnoibat: "",
    motavitri: "",
    congdongdancu: "",
    vegiaoduc: "",
    tienich: "",
    mucgia: 1000000,
  },
];

export default Database;
